apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devpy
  selector:
    matchLabels:
      app: devpy
  template:
    metadata:
      labels:
        app: devpy
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: devpydisk
      containers:
      - name: devpy
        image: devpy:latest
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: ["entrypoint.sh; trap : TERM INT; sleep infinity & wait"]
        ports:
        - containerPort: 3141
        volumeMounts:
        - mountPath: /data
          name: data


